alias: PowerPlan ▸ Řízení akumulace a režimu měniče
description: "Automatizace pro PowerPlan řízení tepelné akumulace, baterie a měniče na základě predikce"
triggers:
  - entity_id:
      - sensor.powerplan_charger_use_mode
      - sensor.powerplan_upper_accumulation_on
      - sensor.powerplan_lower_accumulation_on
      - sensor.powerplan_max_heat_on
      - sensor.powerplan_forced_heating_block
      - sensor.powerplan_battery_discharge_power
      - sensor.powerplan_battery_target_soc
      - sensor.powerplan_reserve_power_charging
      - sensor.powerplan_minimum_battery_soc
    trigger: state
actions:
  # Nastavení režimu měniče
  - target:
      entity_id: select.solax_charger_use_mode
    data:
      option: "{{ powerplan_mode }}"
    action: select.select_option
  
  # Ovládání horní akumulace
  - target:
      entity_id: switch.tepelnaakumulace_povolen_horn_akumulace
    action: |
      {% if powerplan_upper_accu %}
        switch.turn_on
      {% else %}
        switch.turn_off
      {% endif %}
  
  # Ovládání spodní akumulace  
  - target:
      entity_id: switch.tepelnaakumulace_povolen_spodn_akumulace
    action: |
      {% if powerplan_lower_accu %}
        switch.turn_on
      {% else %}
        switch.turn_off
      {% endif %}
  
  # Maximální ohřev ze sítě
  - target:
      entity_id: switch.tepelnaakumulace_maxim_ln_oh_ev_ze_s_t
    action: |
      {% if powerplan_maxh %}
        switch.turn_on
      {% else %}
        switch.turn_off
      {% endif %}
  
  # Blokování nuceného ohřevu
  - target:
      entity_id: switch.tepelnaakumulace_blokov_n_nucen_ho_oh_evu
    action: |
      {% if powerplan_block_heating %}
        switch.turn_on
      {% else %}
        switch.turn_off
      {% endif %}
  
  # Nastavení povoleného vybíjecího výkonu baterie
  - condition: template
    value_template: "{{ powerplan_discharge_power is defined and powerplan_discharge_power | float > 0 }}"
  - target:
      entity_id: number.tepelnaakumulace_povolen_vyb_jec_v_kon_baterie
    data:
      value: "{{ powerplan_discharge_power | float }}"
    action: number.set_value
  
  # Nastavení požadovaného stavu nabití baterie
  - condition: template
    value_template: "{{ powerplan_target_soc is defined and powerplan_target_soc | float > 0 }}"
  - target:
      entity_id: number.tepelnaakumulace_po_adovan_stav_nabit_baterie
    data:
      value: "{{ powerplan_target_soc | float }}"
    action: number.set_value
  
  # Nastavení rezervovaného výkonu pro nabíjení
  - condition: template
    value_template: "{{ powerplan_reserve_power is defined and powerplan_reserve_power | float > 0 }}"
  - target:
      entity_id: number.tepelnaakumulace_rezervovan_v_kon_pro_dob_jen_baterie
    data:
      value: "{{ powerplan_reserve_power | float }}"
    action: number.set_value
  
  # Nastavení minimálního stavu nabití baterie
  - condition: template
    value_template: "{{ powerplan_min_soc is defined and powerplan_min_soc | float > 0 }}"
  - target:
      entity_id: number.tepelnaakumulace_minim_ln_stav_nabit_baterie
    data:
      value: "{{ powerplan_min_soc | float }}"
    action: number.set_value
mode: restart
variables:
  powerplan_mode: "{{ states('sensor.powerplan_charger_use_mode') }}"
  powerplan_upper_accu: "{{ is_state('sensor.powerplan_upper_accumulation_on', 'True') }}"
  powerplan_lower_accu: "{{ is_state('sensor.powerplan_lower_accumulation_on', 'True') }}"
  powerplan_maxh: "{{ is_state('sensor.powerplan_max_heat_on', 'True') }}"
  powerplan_block_heating: "{{ is_state('sensor.powerplan_forced_heating_block', 'True') }}"
  powerplan_discharge_power: "{{ states('sensor.powerplan_battery_discharge_power') | float(0) }}"
  powerplan_target_soc: "{{ states('sensor.powerplan_battery_target_soc') | float(0) }}"
  powerplan_reserve_power: "{{ states('sensor.powerplan_reserve_power_charging') | float(0) }}"
  powerplan_min_soc: "{{ states('sensor.powerplan_minimum_battery_soc') | float(0) }}"
