name: MPC Optimizer
version: "1.0.11"
slug: mpc_optimizer
description: Optimalizace energie s přístupem přes webové rozhraní
startup: services
boot: auto
homeassistant_api: true
hassio_api: true
host_network: true
ingress: true
ingress_port: 26781
ingress_entry: /
panel_icon: mdi:chart-areaspline
panel_title: MPC Optimalizace
icon: 'icon.png'
options:
  token: ""                # výchozí prázdná hodnota
  ha_url: "http://homeassistant:8123"
schema:
  token: str?
  ha_url: str?
arch:
  - amd64
  - aarch64
  - armv7