arch:
- amd64
- aarch64
- armv7
boot: auto
description: "Optimalizace energie s p\u0159\xEDstupem p\u0159es webov\xE9 rozhran\xED"
hassio_api: true
homeassistant_api: true
host_network: true
icon: icon.png
ingress: true
ingress_entry: /
ingress_port: 26781
name: MPC Optimizer
options:
  ha_url: http://homeassistant:8123
  token: ''
panel_icon: mdi:chart-areaspline
panel_title: MPC Optimalizace
schema:
  ha_url: str?
  token: str?
slug: mpc_optimizer
startup: services
version: 1.7.1
