name: MPC Optimizer
version: "1.0.2"
slug: mpc_optimizer
description: Optimalizace energie s přístupem přes webové rozhraní
startup: services
boot: auto
homeassistant_api: true
hassio_api: true
ingress: true
ingress_port: 26781
ingress_entry: /
panel_icon: mdi:chart-areaspline
panel_title: MPC Optimizer
options: {}
schema: {}
arch:
  - amd64
  - aarch64
  - armv7