arch:
- amd64
- aarch64
- armv7
boot: auto
description: intelligent planner and optimizer for energy production and consumption
  with an intuitive web interface
hassio_api: true
homeassistant_api: true
host_network: true
icon: icon.png
ingress: true
ingress_entry: /
ingress_port: 26781
init: false
name: PowerStreamPlan
options:
  ha_url: http://homeassistant:8123
  token: ''
panel_icon: mdi:chart-areaspline
panel_title: PowerStreamPlan
schema:
  ha_url: str?
  token: str?
slug: power_stream_plan
stage: experimental
startup: services
update: true
version: 2.0.2
